---

- name: Install grafana
  apt:
    name: "{{ grafana_package }}"
    state: present

- name: Install grafana_extra_packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ grafana_extra_packages }}"
